# Generated by Django 3.0.5 on 2022-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_trainer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('price', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='EquipmentPic/')),
            ],
        ),
    ]
