# Generated by Django 3.0.5 on 2022-07-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date',
            new_name='joineddate',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
