# Generated by Django 3.0.5 on 2022-07-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gym.Package'),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gym.Trainer'),
        ),
    ]
