# Generated by Django 3.0.5 on 2025-08-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20220721_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Package'),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Trainer'),
        ),
    ]
